apiVersion: v1
kind: Service
metadata:
  name: logto
  namespace: maya-auth
  labels:
    app: logto
    app.kubernetes.io/name: logto
    app.kubernetes.io/part-of: maya
    app.kubernetes.io/component: auth
spec:
  type: ClusterIP
  selector:
    app: logto
  ports:
  - name: http
    port: 3001
    targetPort: http
    protocol: TCP
  - name: admin
    port: 3002
    targetPort: admin
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600