apiVersion: v1
kind: Service
metadata:
  name: main
  namespace: maya-apps
  labels:
    app: main
    app.kubernetes.io/name: main
    app.kubernetes.io/part-of: maya
    app.kubernetes.io/component: backend
  annotations:
    # Prometheus scraping
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: main
  ports:
  - name: http
    port: 3333
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600