# This docker-compose file is for standalone development of the web app
# It imports the necessary services from the root docker-compose.yaml to avoid duplication

name: monitoring-standalone

services:
  # monitoring application
  monitoring:
    container_name: 'monitoring_standalone'
    build:
      context: ../../
      dockerfile: apps/monitoring/Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - ./:/app/apps/monitoring
      - /app/apps/monitoring/node_modules
    networks:
      - maya_network
    depends_on:
      pgsql:
        condition: service_healthy
      ollama:
        condition: service_healthy
    ports:
      - '3333:3333'

  # monitoring worker
  monitoring-worker:
    container_name: 'monitoring_worker_standalone'
    build:
      context: ../../
      dockerfile: apps/monitoring/Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - ./:/app/apps/monitoring
      - /app/apps/monitoring/node_modules
    command: ["node", "ace", "queue:work"]
    networks:
      - maya_network
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_started

  # Import services from the root docker-compose.yaml
  pgsql:
    extends:
      file: ../../docker-compose.yaml
      service: pgsql
    networks:
      - maya_network

  ollama:
    extends:
      file: ../../docker-compose.yaml
      service: ollama
    networks:
      - maya_network

  pgai_vectorizer:
    extends:
      file: ../../docker-compose.yaml
      service: pgai_vectorizer
    networks:
      - maya_network

  init_gemma3:
    extends:
      file: ../../docker-compose.yaml
      service: init_gemma3
    networks:
      - maya_network

  # Required services for monitoring
  redis:
    extends:
      file: ../../docker-compose.yaml
      service: redis
    networks:
      - maya_network

  clickhouse:
    extends:
      file: ../../docker-compose.yaml
      service: clickhouse
    networks:
      - maya_network

  # logto:
  #   extends:
  #     file: ../../docker-compose.yaml
  #     service: logto
  #   networks:
  #     - maya_network

  # logto_postgres:
  #   extends:
  #     file: ../../docker-compose.yaml
  #     service: logto_postgres
  #   networks:
  #     - maya_network

networks:
  maya_network:
    name: maya-adonisjs_maya_network
    external: false
