# This docker-compose file is for standalone development of the web app
# It imports the necessary services from the root docker-compose.yaml to avoid duplication

name: main-standalone

services:
  # Main application
  main:
    container_name: 'main_standalone'
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - ./:/app/apps/web
      - /app/apps/web/node_modules
    networks:
      - maya_network
    depends_on:
      pgsql:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      HOST: 0.0.0.0
      PORT: 3333
      NODE_ENV: development
      DB_HOST: pgsql
      REDIS_HOST: redis
      CLICKHOUSE_HOST: clickhouse
      LOGTO_ENDPOINT: http://logto:3001
      LOGTO_ADMIN_ENDPOINT: http://logto:3002
    ports:
      - '3333:3333'

  # Import services from the root docker-compose.yaml
  pgsql:
    extends:
      file: ../../docker-compose.yaml
      service: pgsql
    networks:
      - maya_network

  ollama:
    extends:
      file: ../../docker-compose.yaml
      service: ollama
    networks:
      - maya_network

  pgai_vectorizer:
    extends:
      file: ../../docker-compose.yaml
      service: pgai_vectorizer
    networks:
      - maya_network

  init_gemma3:
    extends:
      file: ../../docker-compose.yaml
      service: init_gemma3
    networks:
      - maya_network

  # Optional services - uncomment if needed
  # redis:
  #   extends:
  #     file: ../../docker-compose.yaml
  #     service: redis
  #   networks:
  #     - maya_network

  # clickhouse:
  #   extends:
  #     file: ../../docker-compose.yaml
  #     service: clickhouse
  #   networks:
  #     - maya_network

  # logto:
  #   extends:
  #     file: ../../docker-compose.yaml
  #     service: logto
  #   networks:
  #     - maya_network

  # logto_postgres:
  #   extends:
  #     file: ../../docker-compose.yaml
  #     service: logto_postgres
  #   networks:
  #     - maya_network

networks:
  maya_network:
    name: maya-adonisjs_maya_network
    external: false
