apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logto-data
  namespace: maya-auth
  labels:
    app: logto
    app.kubernetes.io/name: logto
    app.kubernetes.io/part-of: maya
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi