apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: maya-apps
  labels:
    app: mailhog
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/part-of: maya
    app.kubernetes.io/component: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
        app.kubernetes.io/name: mailhog
        app.kubernetes.io/part-of: maya
        app.kubernetes.io/component: email
    spec:
      serviceAccountName: mailhog
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: mailhog
        image: mailhog/mailhog:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: smtp
          containerPort: 1025
          protocol: TCP
        - name: http
          containerPort: 8025
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: smtp
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: smtp
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mailhog
  namespace: maya-apps
  labels:
    app: mailhog
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/part-of: maya