apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maya-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: development
    app.kubernetes.io/part-of: maya
spec:
  project: maya
  
  source:
    repoURL: https://github.com/your-org/maya-adonisjs
    targetRevision: main
    path: infra/kubernetes/overlays/dev
    
    # Kustomize specific config
    kustomize:
      images:
      - ghcr.io/your-org/maya-main:dev-${ARGOCD_APP_REVISION}
      - ghcr.io/your-org/maya-monitoring:dev-${ARGOCD_APP_REVISION}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: maya-apps
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  # Health checks
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    jsonPointers:
    - /spec/minReplicas
    - /spec/maxReplicas